import type { NextConfig } from "next";

/**
 * Security headers applied to every response. Tuned for Quizen specifically:
 *  - We talk to Supabase + Anthropic + Gemini + Stripe + Sentry +
 *    PostHog — connect-src covers all of them.
 *  - We render no third-party iframes except Stripe's checkout (handled by
 *    Stripe's hosted URL via window.location, not embedded) — frame-src
 *    stays "self" only.
 *  - SVG icons live in /public — img-src includes 'self' + data: for inline
 *    icon assets generated by Lucide.
 *  - upgrade-insecure-requests forces http→https on any stray asset URL.
 *
 * If you change which third-party services Quizen calls, update connect-src
 * here. Otherwise the call will be blocked silently by the browser.
 */
const SECURITY_HEADERS = [
  {
    key: "Strict-Transport-Security",
    value: "max-age=63072000; includeSubDomains; preload",
  },
  {
    key: "X-Content-Type-Options",
    value: "nosniff",
  },
  {
    key: "X-Frame-Options",
    value: "DENY",
  },
  {
    key: "Referrer-Policy",
    value: "strict-origin-when-cross-origin",
  },
  {
    key: "Permissions-Policy",
    value: "camera=(), microphone=(), geolocation=(), interest-cohort=()",
  },
  {
    key: "Content-Security-Policy",
    value: [
      "default-src 'self'",
      // 'unsafe-inline' needed for Next inline scripts; 'unsafe-eval' for dev only — Next handles
      "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://js.stripe.com",
      "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
      "font-src 'self' https://fonts.gstatic.com data:",
      "img-src 'self' data: blob: https:",
      "media-src 'self'",
      "connect-src 'self' https://*.supabase.co https://*.supabase.in wss://*.supabase.co https://api.anthropic.com https://generativelanguage.googleapis.com https://api.stripe.com https://*.sentry.io https://*.posthog.com https://*.upstash.io",
      "frame-src 'self' https://js.stripe.com https://hooks.stripe.com",
      "worker-src 'self' blob:",
      "manifest-src 'self'",
      "object-src 'none'",
      "base-uri 'self'",
      "form-action 'self'",
      "frame-ancestors 'none'",
      "upgrade-insecure-requests",
    ].join("; "),
  },
];

const nextConfig: NextConfig = {
  async headers() {
    return [
      {
        source: "/:path*",
        headers: SECURITY_HEADERS,
      },
    ];
  },
};

export default nextConfig;
